name: polarity-pde
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - matplotlib
  - scipy
  - ipywidgets
  - jupyter
  - pandas
  - pip
  - pip:
      - polarity-pde==0.1.2
